//
// Created by kenne on 25/02/2025.
//

#pragma once

#include "fxt/monad/AndThen.hpp"
#include "fxt/monad/Expected.hpp"
#include "fxt/monad/LogicalOr.hpp"
#include "fxt/monad/Match.hpp"
#include "fxt/monad/Optional.hpp"
#include "fxt/monad/OrElse.hpp"
#include "fxt/monad/Tap.hpp"
#include "fxt/monad/ToExpected.hpp"
#include "fxt/monad/ToOptional.hpp"
#include "fxt/monad/Transform.hpp"
#include "fxt/monad/TransformError.hpp"
#include "fxt/monad/Value.hpp"
#include "fxt/monad/ValueOr.hpp"
#include "fxt/tuple/Append.hpp"
#include "fxt/tuple/Apply.hpp"
#include "fxt/tuple/Drop.hpp"
#include "fxt/tuple/FlatTuple.hpp"
#include "fxt/tuple/Get.hpp"
#include "fxt/tuple/Select.hpp"
#include "fxt/tuple/Take.hpp"
#include "fxt/tuple/Tuple.hpp"
#include "fxt/tuple/TupleAppend.hpp"
#include "fxt/tuple/TupleSize.hpp"
#include "fxt/utils/Curry.hpp"
#include "fxt/utils/Failure.hpp"
#include "fxt/utils/Lift.hpp"
#include "fxt/utils/Overload.hpp"
#include "fxt/utils/Type.hpp"
#include "fxt/utils/Unit.hpp"