//
// Created by kenne on 25/02/2025.
//

#pragma once

#include "fxt/concepts/IsExpected.hpp"
#include "fxt/concepts/IsOptional.hpp"
#include "fxt/concepts/IsTuple.hpp"
#include "fxt/concepts/IsMonad.hpp"
#include "fxt/monads/AndThen.hpp"
#include "fxt/monads/Expected.hpp"
#include "fxt/monads/LogicalOr.hpp"
#include "fxt/monads/Match.hpp"
#include "fxt/monads/Optional.hpp"
#include "fxt/monads/OrElse.hpp"
#include "fxt/monads/Tap.hpp"
#include "fxt/monads/ToExpected.hpp"
#include "fxt/monads/ToOptional.hpp"
#include "fxt/monads/Transform.hpp"
#include "fxt/monads/TransformError.hpp"
#include "fxt/monads/Value.hpp"
#include "fxt/monads/ValueOr.hpp"
#include "fxt/tuples/Append.hpp"
#include "fxt/tuples/Apply.hpp"
#include "fxt/tuples/Drop.hpp"
#include "fxt/tuples/FlatTuple.hpp"
#include "fxt/tuples/Get.hpp"
#include "fxt/tuples/Select.hpp"
#include "fxt/tuples/Take.hpp"
#include "fxt/tuples/Transform.hpp"
#include "fxt/tuples/Tuple.hpp"
#include "fxt/tuples/TupleAppend.hpp"
#include "fxt/tuples/TupleElement.hpp"
#include "fxt/tuples/TupleSize.hpp"
#include "fxt/utils/Curry.hpp"
#include "fxt/utils/Failure.hpp"
#include "fxt/utils/Lift.hpp"
#include "fxt/utils/Overload.hpp"
#include "fxt/utils/Type.hpp"
#include "fxt/utils/Unit.hpp"